export const CONTATO_LISTAR = 'CONTATO_LISTAR';
export const CONTATO_INCLUIR = 'CONTATO_INCLUIR';
export const CONTATO_IMAGEM = 'CONTATO_IMAGEM';
export const CONTATO_NOME = 'CONTATO_NOME';
export const CONTATO_TELEFONE = 'CONTATO_TELEFONE';
export const CONTATO_REMOVER = 'CONTATO_REMOVER';
